### ISSUE TITLE
Publish 1.4 to mod platforms

### ISSUE THREAD

**Issue by Madis0** [FakeDomi/FastChest#26]
V1.4 of the mod seems to be out, but it is not on CurseForge yet, please publish it there. Similarly, publishing to Modrinth would be nice, it does support author payments now.

**Comment by RoonMoonlight** [comment]
Made #27 about modrinth support, and I don't think they are going back into CurseForge because author officially stated they are not updating on that platform anymore

**Comment by FakeDomi** [comment]
I won't be publishing my mods on either site anymore. I'm disagreeing with Curseforge's shitty practices, and with Modrinth moderators' stance on bans.
Since pretty much everything I do is licensed under MIT anyone could upload my mods to their favorite mod site and even receive payouts. But Github is the only official place as of now.
