### ISSUE TITLE
Hatch renders even if removed in resource pack

### ISSUE THREAD

**Issue by Brottweiler** [FakeDomi/FastChest#4]
Hey!

In my resource pack, I have removed the hatch from the chest, so there's no 3D hatch texture poking out from the chest texture. Using FastChest, it renders the hatch back in for some reason.
![image](https://user-images.githubusercontent.com/1613137/107146412-546e2b00-6948-11eb-9973-df003ec5fb78.png)
![image](https://user-images.githubusercontent.com/1613137/107146458-b9298580-6948-11eb-8275-46c3029a1536.png)
The texture the arrow points to is deleted from the texture, but the hatch still renders.

**Comment by FakeDomi** [comment]
That's happening because the model doesn't support transparency. And I don't think I want to enable that for just this specific use case.

What you can do however is adding the `template_...` files from this mod's `/assets/minecraft/models/block/` directory to your resource pack and removing the latch from these models. It's the third element in all three templates.

**Comment by Brottweiler** [comment]
Wow! Thank you, this worked perfectly!

This way I also managed to make the chest render as a full block. The texture is still 14x14 but renders as a full block. Probably makes no difference to performance but I prefer it this way. :) Thanks again!
